# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python
name: django4

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  django4:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
        pip install -r tests/django5.txt

    - name: flake8
      run: |
        flake8 --count --show-source --statistics --max-line-length=120 django_admin_geomap
        flake8 --count --show-source --statistics --max-line-length=120 tests/test

    - name: pylint
      run: |
        python -m pylint django_admin_geomap
        python -m pylint tests/test

    - name: pytest
      run: |
        python manage.py collectstatic --noinput --settings example.settings
        python manage.py makemigrations --settings example.settings example
        python manage.py migrate --settings example.settings
        pytest -c pytest4.ini --cov=django_admin_geomap --cov-report xml --cov-report term:skip-covered --durations=5 tests
