# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python
name: geomap-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  django3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
        pip install -r tests/django3.txt

    - name: flake8
      run: |
        flake8 --count --show-source --statistics --max-line-length=120 django_admin_geomap
        flake8 --count --show-source --statistics --max-line-length=120 tests/test

    - name: pylint
      run: |
        python -m pylint --load-plugins=pylint.extensions.mccabe --max-complexity=10 --init-hook="import sys;sys.path.insert(0, './')" --load-plugins pylint_django --django-settings-module=example.settings --disable=relative-import django_admin_geomap
        python -m pylint --load-plugins=pylint.extensions.mccabe --max-complexity=10 --init-hook="import sys;sys.path.insert(0, './')" --load-plugins pylint_django --django-settings-module=example.settings --disable=relative-import tests/test

    - name: pytest
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        python manage.py collectstatic --noinput --settings example.settings
        python manage.py makemigrations --settings example.settings example
        python manage.py migrate --settings example.settings
        pytest --cov=django_admin_geomap --cov-report xml --cov-report term:skip-covered --durations=5 tests
        python-codacy-coverage -r coverage.xml
